import { AlertItem } from "@/types/alert.type";

export const dummyAlertItems: AlertItem[] = [
  {
    id: "alert-001",
    sender: "Telkomsel",
    source: "SMS",
    time: "09:42 AM",
    date: "Today",
    timestamp: Date.now() - 1000 * 60 * 15,
    score: 92,
    unread: true,
  },
  {
    id: "alert-002",
    sender: "BRI-INFO",
    source: "SMS",
    time: "08:18 AM",
    date: "Today",
    timestamp: Date.now() - 1000 * 60 * 90,
    score: 87,
    unread: true,
  },
  {
    id: "alert-003",
    sender: "DANA",
    source: "SMS",
    time: "07:55 AM",
    date: "Today",
    timestamp: Date.now() - 1000 * 60 * 140,
    score: 74,
    unread: false,
  },
  {
    id: "alert-004",
    sender: "Shopee",
    source: "SMS",
    time: "10:30 PM",
    date: "Yesterday",
    timestamp: Date.now() - 1000 * 60 * 60 * 18,
    score: 68,
    unread: false,
  },
  {
    id: "alert-005",
    sender: "GoPay",
    source: "SMS",
    time: "06:14 PM",
    date: "Yesterday",
    timestamp: Date.now() - 1000 * 60 * 60 * 23,
    score: 81,
    unread: true,
  },
  {
    id: "alert-006",
    sender: "Unknown",
    source: "SMS",
    time: "03:22 PM",
    date: "Yesterday",
    timestamp: Date.now() - 1000 * 60 * 60 * 27,
    score: 95,
    unread: false,
  },
  {
    id: "alert-007",
    sender: "Mandiri",
    source: "SMS",
    time: "11:08 AM",
    date: "30 Sept 2026",
    timestamp: Date.now() - 1000 * 60 * 60 * 72,
    score: 89,
    unread: false,
  },
  {
    id: "alert-008",
    sender: "PromoID",
    source: "SMS",
    time: "02:45 PM",
    date: "29 Sept 2026",
    timestamp: Date.now() - 1000 * 60 * 60 * 96,
    score: 61,
    unread: false,
  },
];